2019-10-09 16:04:09,484 INFO Connecting to TGC socket...
2019-10-09 16:04:10,490 INFO Connected.
2019-10-09 16:04:10,490 INFO Recording brain data...
2019-10-09 16:14:19,253 INFO Connecting to TGC socket...
2019-10-09 16:14:20,261 INFO Connected.
2019-10-09 16:14:20,262 INFO Recording brain data...
2019-10-09 16:20:18,963 INFO Connecting to TGC socket...
2019-10-09 16:20:19,970 INFO Connected.
2019-10-09 16:20:19,971 INFO Recording brain data...
2019-10-09 16:23:36,732 INFO Connecting to TGC socket...
2019-10-09 16:23:37,740 INFO Connected.
2019-10-09 16:23:37,740 INFO Recording brain data...
2019-10-09 16:24:13,564 INFO Connecting to TGC socket...
2019-10-09 16:24:14,572 INFO Connected.
2019-10-09 16:24:14,573 INFO Recording brain data...
2019-10-09 16:24:41,642 INFO Connecting to TGC socket...
2019-10-09 16:24:42,649 INFO Connected.
2019-10-09 16:24:42,649 INFO Recording brain data...
2019-10-09 16:26:21,836 INFO Connecting to TGC socket...
2019-10-09 16:26:22,844 INFO Connected.
2019-10-09 16:26:22,844 INFO Recording brain data...
2019-10-09 16:26:23,391 ERROR Exception:
Traceback (most recent call last):
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 120, in <module>
    conn.record_data()
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 82, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-09 16:26:23,392 ERROR No connection with TGC socket
2019-10-09 16:27:15,935 INFO Connecting to TGC socket...
2019-10-09 16:27:16,941 INFO Connected.
2019-10-09 16:27:16,941 INFO Recording brain data...
2019-10-09 16:27:47,461 INFO Connecting to TGC socket...
2019-10-09 16:27:48,469 INFO Connected.
2019-10-09 16:27:48,469 INFO Recording brain data...
2019-10-09 16:31:46,148 INFO Connecting to TGC socket...
2019-10-09 16:31:47,156 INFO Connected.
2019-10-09 16:31:47,156 INFO Recording brain data...
2019-10-09 16:34:36,393 INFO Connecting to TGC socket...
2019-10-09 16:34:37,401 INFO Connected.
2019-10-09 16:34:37,401 INFO Recording brain data...
2019-10-09 16:35:55,780 INFO Connecting to TGC socket...
2019-10-09 16:35:56,786 INFO Connected.
2019-10-09 16:35:56,786 INFO Recording brain data...
2019-10-09 16:39:51,790 INFO Connecting to TGC socket...
2019-10-09 16:39:52,797 INFO Connected.
2019-10-09 16:39:52,797 INFO Recording brain data...
2019-10-09 16:40:53,410 INFO Connecting to TGC socket...
2019-10-09 16:40:54,416 INFO Connected.
2019-10-09 16:40:54,416 INFO Recording brain data...
2019-10-09 16:48:55,952 INFO Connecting to TGC socket...
2019-10-09 16:48:56,960 INFO Connected.
2019-10-09 16:48:56,960 INFO Recording brain data...
2019-10-09 16:55:05,923 INFO Connecting to TGC socket...
2019-10-09 16:55:06,935 INFO Connected.
2019-10-09 16:55:06,935 INFO Recording brain data...
2019-10-09 16:58:29,491 INFO Connecting to TGC socket...
2019-10-09 16:58:30,505 INFO Connected.
2019-10-09 16:58:30,505 INFO Recording brain data...
2019-10-09 16:59:10,340 INFO Connecting to TGC socket...
2019-10-09 16:59:11,353 INFO Connected.
2019-10-09 16:59:11,354 INFO Recording brain data...
2019-10-09 16:59:12,104 ERROR Exception:
Traceback (most recent call last):
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 121, in <module>
    conn.record_data()
  File "D:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 82, in record_data
    self.data = self.data.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 0: ordinal not in range(128)
2019-10-09 16:59:12,104 ERROR No connection with TGC socket
2019-10-09 17:00:12,095 INFO Connecting to TGC socket...
2019-10-09 17:00:13,106 INFO Connected.
2019-10-09 17:00:13,107 INFO Recording brain data...
2019-10-09 20:56:26,989 INFO Connecting to TGC socket...
2019-10-09 20:56:29,292 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:56:29,375 ERROR No connection with TGC socket
2019-10-09 20:58:28,082 INFO Connecting to TGC socket...
2019-10-09 20:58:30,092 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:58:30,096 ERROR No connection with TGC socket
2019-10-09 20:58:59,909 INFO Connecting to TGC socket...
2019-10-09 20:59:01,917 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:01,921 ERROR No connection with TGC socket
2019-10-09 20:59:08,244 INFO Connecting to TGC socket...
2019-10-09 20:59:10,255 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:10,259 ERROR No connection with TGC socket
2019-10-09 20:59:50,492 INFO Connecting to TGC socket...
2019-10-09 20:59:52,507 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:52,509 ERROR No connection with TGC socket
2019-10-09 20:59:52,924 INFO Connecting to TGC socket...
2019-10-09 20:59:54,932 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 20:59:54,934 ERROR No connection with TGC socket
2019-10-09 21:00:18,824 INFO Connecting to TGC socket...
2019-10-09 21:00:20,833 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 21:00:20,834 ERROR No connection with TGC socket
2019-10-09 21:00:40,501 INFO Connecting to TGC socket...
2019-10-09 21:00:42,510 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 21:00:42,514 ERROR No connection with TGC socket
2019-10-09 21:00:50,200 INFO Connecting to TGC socket...
2019-10-09 21:00:52,211 ERROR Exception:
Traceback (most recent call last):
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 118, in <module>
    conn.connect(TGHOST, TGPORT)
  File "E:\Brain-Keyboard\Reference Codes\Neurosky Telnet Conn\recordEEGdata.py", line 49, in connect
    self.sock = Telnet('localhost',13854)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\ProgramData\Anaconda3\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2019-10-09 21:00:52,215 ERROR No connection with TGC socket
2019-10-09 21:17:21,107 INFO Connecting to TGC socket...
2019-10-09 21:17:22,115 INFO Connected.
2019-10-09 21:17:22,148 INFO Recording brain data...
2019-10-09 21:30:05,139 INFO Connecting to TGC socket...
2019-10-09 21:30:06,148 INFO Connected.
2019-10-09 21:30:06,148 INFO Recording brain data...
